# Generated by Django 5.2.6 on 2026-02-01 21:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(max_length=50)),
                ('Student_Surname', models.CharField(max_length=50)),
                ('Student_Address', models.TextField()),
                ('Student_Email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('Student_Number', models.CharField(max_length=15)),
                ('Student_DOB', models.DateField()),
                ('Student_Age', models.PositiveIntegerField(editable=False)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.courseslot')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianModel',
            fields=[
                ('Guardian_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Guardian_Name', models.CharField(max_length=50)),
                ('Guardian_Surname', models.CharField(max_length=50)),
                ('Guardian_Address', models.TextField()),
                ('Guardian_Number', models.CharField(max_length=15)),
                ('Guardian_Email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('Guardian_Relationship_to_student', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('legal_guardian', 'Legal Guardian'), ('step_parent', 'Step Parent'), ('foster_parent', 'Foster Parent')], max_length=20)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='app1.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Booking_Name', models.CharField(max_length=30)),
                ('Booking_email', models.EmailField(max_length=254)),
                ('Booking_Party_Size', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=5)),
                ('Booking_Location', models.CharField(choices=[('Campus 1', 'Campus 1'), ('Campus 2', 'Campus 2'), ('Campus 3', 'Campus 3')], default='Campus 1', max_length=10)),
                ('Booking_Additional_Needs', models.CharField(choices=[('Accessibility accommodations', 'Accessibility accommodations: ramps, elevators, seating.'), ('Food and dietery options', 'Food and dietary options: vegetarian, vegan, halal, kosher, or allergy-aware refreshments.'), ('N/A', 'N/A')], default='N/A', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('Booking_Date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.availabledate')),
                ('addons', models.ManyToManyField(blank=True, to='app1.addon')),
                ('Booking_Time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.timeslot')),
            ],
        ),
    ]
